[package]
name = "batching_queue"
version = "0.1.0"
edition = "2021"

[dependencies]
cache-padded = "1.1.1"
futures = "0.3.17"

[dev-dependencies]
itertools = "0.10.3"
tokio = { version = "1.15.0", features = ["macros", "rt-multi-thread"] }
